services:
    angular:
        container_name: loteria-api-angular
        build:
            context: docker
            dockerfile: angular
        restart: always
        volumes:
            - ./loteria:/app
        working_dir: /app
        ports:
            - 4200:4200