services:
  mariadb:
    container_name: loteria-mariadb
    image: mariadb:latest
    working_dir: /app
    ports: 
      - 3306:3306
    environment:
      - MARIADB_ROOT_PASSWORD=loteria
      - MARIADB_DATABASE=loteria
      - MARIADB_USER=loteria
      - MARIADB_PASSWORD=loteria
    volumes:
      - type: volume
        source: mariadb
        target: /var/lib/mysql
      - .:/app
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "loteria", "--password=loteria"]
      interval: 10s     # Verifica a cada 10 segundos
      timeout: 5s       # O comando deve responder em até 5 segundos
      retries: 3        # Após 3 falhas consecutivas, o container será marcado como unhealthy
      start_period: 30s # Aguarda 30 segundos antes de iniciar as verificações
  
  phpmyadmin:
    container_name: loteria-phpmyadmin
    image: phpmyadmin:latest
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=loteria
      - MYSQL_USER=loteria
      - MYSQL_PASSWORD=loteria
      - PMA_HOST=db
      - PMA_PORT=3306
      - PMA_USER=loteria
      - PMA_PASSWORD=loteria
      - PMA_PMADB=loteria
      # - PMA_ARBITRARY=0
    ports:
      - 8080:80
    depends_on:
      - mariadb
    links:
      - mariadb:db
  
#  mail:
#    container_name: loteria-mail
#    image: mailhog/mailhog:latest
#    restart: always
#    ports:
#      - 8025:8025
#      - 1025:1025
#            
#  redis:
#    container_name: loteria-redis
#    image: redis:latest
#    restart: always
#    ports:
#      - 6379:6379
  
#  nginx:
#    container_name: loteria-nginx
#    image: nginx:1.27.4-bookworm
#    volumes:
#      - .:/var/www/app
#      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
#    ports: 
#      - 80:80
#    environment:
#      - NGINX_HOST=loteria.paginaemconstrucao.com.br
#      - NGINX_PORT=80
#    depends_on:
#      - php-fpm
  
  httpd:
    container_name: loteria-httpd
    image: httpd:2.4.63-alpine
    ports: 
      - 3000:80
    volumes:
      - .:/usr/local/apache2/htdocs
      - ./docker/httpd/httpd.conf:/usr/local/apache2/conf/httpd.conf
    working_dir: /usr/local/apache2/htdocs
    depends_on:
      - php-fpm
    links:
      - php-fpm
      
  php-fpm:
    container_name: loteria-php-fpm
    build: 
        context: docker
        dockerfile: Dockerfile-php-fpm
    restart: always
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
#    ports: 9000:9000
    links:
      - mariadb
#      - mail
#      - redis
    depends_on:
      - mariadb
#      - mail
#      - redis

volumes:
  mariadb:
    name: loteria-mariadb-volume