
FROM ubuntu:latest

ENV timezone=America/Sao_Paulo

RUN apt update \
    && apt full-upgrade -y

RUN ln -snf /usr/share/zoneinfo/${timezone} /etc/localtime && echo ${timezone} > /etc/timezone

RUN apt install -y ca-certificates apt-transport-https software-properties-common lsb-release

RUN add-apt-repository ppa:ondrej/php -y

RUN apt update

RUN apt install -y apache2 php-fpm php-xml php-intl php-mysql curl php-curl

RUN a2enmod proxy_fcgi setenvif \
    && a2enconf php8.3-fpm

COPY etc/apache2/apache2.conf /etc/apache2/apache2.conf

COPY etc/apache2/sites-available/000-default.conf /etc/apache2/sites-available/000-default.conf

RUN mkdir /var/www/loteria-api && mkdir /var/www/loteria-api/public

RUN ln -s -d /var/www/loteria-api/public/ /var/www/html/loteria-api

EXPOSE 80

WORKDIR /var/www/loteria-api

ENTRYPOINT /etc/init.d/php8.3-fpm start && /etc/init.d/apache2 start && /bin/bash

CMD ["true"]