-- MySQL Script generated by MySQL Workbench
-- Sun Feb 18 07:21:42 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema loteria
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema loteria
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `loteria` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci ;
USE `loteria` ;

-- -----------------------------------------------------
-- Table `loteria`.`loteria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `loteria`.`loteria` (
  `id` BINARY(16) NOT NULL,
  `nome` VARCHAR(60) NOT NULL,
  `slug` VARCHAR(120) NOT NULL,
  `api` VARCHAR(255) NOT NULL,
  `marcar` JSON NOT NULL,
  `dezenas` JSON NOT NULL,
  `premiar` JSON NOT NULL,
  `is_active` TINYINT(1) NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `nome_UNIQUE` (`nome` ASC) VISIBLE,
  UNIQUE INDEX `slug_UNIQUE` (`slug` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `loteria`.`concurso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `loteria`.`concurso` (
  `id` BINARY(16) NOT NULL,
  `numero` INT UNSIGNED NOT NULL,
  `loteria_id` BINARY(16) NOT NULL,
  `dezenas` JSON NOT NULL,
  `apuracao` TIMESTAMP NULL,
  `rateio` JSON NULL,
  `local` VARCHAR(60) NULL,
  `municipio` VARCHAR(60) NULL,
  `uf` VARCHAR(2) NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_concurso_loteria_idx` (`loteria_id` ASC) VISIBLE,
  INDEX `numero_INDEX` (`numero` DESC, `loteria_id` ASC) VISIBLE,
  CONSTRAINT `fk_concurso_loteria`
    FOREIGN KEY (`loteria_id`)
    REFERENCES `loteria`.`loteria` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `loteria`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `loteria`.`usuario` (
  `id` BINARY(16) NOT NULL,
  `nome` VARCHAR(60) NOT NULL,
  `celular` VARCHAR(20) NULL,
  `email` VARCHAR(180) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `roles` JSON NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL,
  `last_login_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  INDEX `login_INDEX` (`email` ASC, `password` ASC) VISIBLE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
