
FROM php:fpm

RUN apt update -y

RUN apt install -y libicu-dev

RUN docker-php-ext-configure intl

RUN docker-php-ext-configure pdo_mysql --with-pdo-mysql=mysqlnd

RUN docker-php-ext-install intl pdo pdo_mysql opcache

ADD etc/php/php-extra.ini /usr/local/etc/php/conf.d/php-extra.ini

WORKDIR /app