FROM php:8.4.5-fpm-bookworm

RUN apt update -y \
    && apt install -y libicu-dev zlib1g-dev libpng-dev libjpeg-dev libfreetype6-dev libonig-dev \
    && pecl install redis \
    && docker-php-ext-enable redis \
    && docker-php-ext-install intl \
    && docker-php-ext-install pdo \
    && docker-php-ext-install pdo_mysql \
    && docker-php-ext-install gd \
    && docker-php-ext-install mbstring

WORKDIR /var/www/html

# Expor a porta 9000
EXPOSE 9000

# Definir o comando padrão
CMD ["php-fpm"]